---

- name: Update hostname in /etc/sysconfig/network
  lineinfile:
    dest: /etc/sysconfig/network
    line: "HOSTNAME=\"{% if __hostname_fqdn_defined | default(False) %}{{ hostname_fqdn }}{% else %}{{ hostname_short }}{% endif %}\""
    regexp: "^HOSTNAME="
    state: present
    validate: sh -n %s
